export const USER_INIT = 'USER_INIT'
export const DB_USERS_INIT = 'DB_USERS_INIT'
export const DB_SPOTS_INIT = 'DB_SPOTS_INIT'
export const LOGIN_ACTION = 'LOGIN_ACTION'
export const ADD_SPOT_ACTION = 'ADD_SPOT_ACTION'